markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/

gauges_id:
google_analytics_id: --
google_site_verification:

repository: https://github.com/JoinJohn/plus.github.io/
help_url: https://github.com/JoinJohn/plus.github.-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true

name: Cloud I have xxtra...? • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://

twitter:
  username: 

logo: img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore
